name: Daily YouTube Banner Update

on:
  schedule:
    # Runs every day at 1:00 AM UTC
    - cron: "0 1 * * *"

  workflow_dispatch:  # Allows manual triggering from GitHub Actions
    {}

jobs:
  update-banner:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Adjust based on your script compatibility

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow google-api-python-client google-auth google-auth-oauthlib

      # Step 4: Add Google credentials
      - name: Add Google credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: echo "$GOOGLE_APPLICATION_CREDENTIALS" > client_secret.json

      # Step 5: Run the Python script
      - name: Run Python script
        run: python main.py
